Repository yeonjuan/TypeScript-Handbook-ko, pull requests merged in 2020-02, with the labels that each got.

#4 variable-declarations ~ const declarations 까지 번역 (ref #3)
  variable-declarations.md
Labels: 번역 담당

#6 interfaces 번역 ~ Our First Interface
  interfaces.md
Labels: 번역 담당

#12 Basic Types 오타 및 의역 수정
  basic-types.md
Labels: 오타/잘못된 내용

#13 Basic Types 오타 및 맞춤법 수정
  basic-types.md
Labels: 오타/잘못된 내용

#16 Classes 번역 ~ Clasess
  classes.md
Labels: 번역 담당

#15 interfaces 번역 ~Optional Properties
  interfaces.md
Labels: 번역 담당

#22 interfaces 번역 ~ Readonly Properties
  interfaces.md
Labels: 번역 담당

#26 Classes 번역 ~ Inheritance (ref #2)
  classes.md
Labels: 번역 담당

#18 variable-declarations ~ property renaming 까지 번역 (ref #3)
  variable-declarations.md
Labels: 번역 담당

#25 basic types 오타 수정 (fixes #24)
  basic-types.md
Labels: 오타/잘못된 내용

#30 Classes 번역 ~ Public, private and protected modifiers (#ref 2)
  classes.md
Labels: 번역 담당

#31 Classes 번역 ~ Readonly modifier
  classes.md
Labels: 번역 담당

#27 interfaces 번역 ~ Excess Property Checks
  interfaces.md
Labels: 번역 담당

#33 Classes 번역 ~ Accessors (ref #2)
  classes.md
Labels: 번역 담당

#21 Functions 전체 번역완료
  README.md
  functions.md
Labels: 번역 담당

#37 Classes 번역 ~ Abstract Classes(ref #2)
  classes.md
Labels: 번역 담당

#39 Classes 번역 ~ Advanced Techniques(ref #2)
  classes.md
Labels: 번역 담당

#29 variable-declarations 번역 (fixes #3)
  README.md
  variable-declarations.md
Labels: 번역 담당

#42 Enums 번역
  enums.md
Labels: 번역 담당

#46 symbols 번역 (fixes #28)
  symbols.md
Labels: 번역 담당

#61 일부 오역 수정 및 누락된 기호 추가 (ref #60)
  classes.md
Labels: 오타/잘못된 내용

#55 규칙에 맞게 수정
  variable-declarations.md
Labels: 오타/잘못된 내용

#64 Triple-Slash Directives 첫 문단 번역 (ref #59)
  README.md
  triple-slash-directives.md
Labels: 번역 담당

#62 interfaces 번역 ~ 끝
  interfaces.md
Labels: 번역 담당

#67 Triple-Slash Directives reference path 번역
  triple-slash-directives.md
Labels: 번역 담당

#69 Iterators and Generators 번역 #53
  README.md
  iterators-and-generators.md
Labels: 번역 담당

#72 advance types 번역 ~ union types
  advanced-types.md
Labels: 번역 담당

#76 Interfaces 오타/오역/md깨지는 부분 수정 (ref #68)
  interfaces.md
Labels: 번역 담당

#73 Type Compatibility 번역 ~ Advanced Topics (ref #40)
  README.md
  type-compatibility.md
Labels: 번역 담당

#74 Modules 번역 ~ Default exports (ref #51)
  modules.md
Labels: 번역 담당

#78 Modules 번역 ~ export = and import = require()(ref #51)
  modules.md
Labels: 번역 담당

#84 ^B / ^] 문자 제거
  classes.md
Labels: 오타/잘못된 내용

#79 advanced types 번역 ~ user-defined type guards (ref #63)
  advanced-types.md
Labels: 번역 담당

#85 Type Inference 수정 (ref #80)
  type-inference.md
Labels: 오타/잘못된 내용

#91 functions ~함수 오역 수정
  functions.md
Labels: 오타/잘못된 내용

#89 ~reference types 번역 (ref #59)
  .markdownlintignore
  triple-slash-directives.md
Labels: 번역 담당

#97 advanced-types 번역 ~ nullable types (ref #63)
  advanced-types.md
Labels: 번역 담당

#98 ~ reference lib 까지 번역 (ref #59)
  triple-slash-directives.md
Labels: 번역 담당

#99 release3.8 번역 ~ bumkeyy
  release-notes/typescript-3.8.md
Labels: 번역 담당

#96 Declaration Merging 번역 ~ 끝 (ref #86)
  declaration-merging.md
  jsx.md
Labels: 번역 담당

#113 Modules 번역 ~ Optional Module Loading and Other Advanced Loading Scenarios (ref #51)
  README.md
  modules.md
Labels: 번역중

#114 advaced types 번역 ~ Enum member types
  advanced-types.md
Labels: 번역중

#115 Modules 번역 ~ Working with Other JavaScript Libraries (ref #51)
  modules.md
Labels: 번역중

#116 Triple-Slash Directives 번역 끝 (fixes #59)
  README.md
  triple-slash-directives.md
Labels: 번역중

#117 Namespaces 번역 완료 (#70)
  README.md
  namespaces.md
Labels: 번역중
