Repository yeonjuan/TypeScript-Handbook-ko, pull requests merged in 2020-04, with the labels that each got.

#174 iterator 용어 통일 및 제목 형식 수정
  iterators-and-generators.md
Labels: 오타 / 잘못된 내용

#183 JSX 검토
  .markdownlint.json
  jsx.md
Labels: 오타 / 잘못된 내용

#188 Declaration Files/By Example 번역 완료 (#145)
  declaration files/By Example.md
Labels: 번역중

#191 namespaces and modules 검토
  namespaces-and-modules.md
Labels: 오타 / 잘못된 내용

#187 namespaces 검토 완료
  namespaces.md
Labels: 오타 / 잘못된 내용

#189 Modules 검토 완료
  modules.md
Labels: 오타 / 잘못된 내용

#181 Library Structures 번역 ~ global libraries
  declaration files/Library Structures.md
Labels: 번역중

#182 Advanced Types 검토 완료
  advanced-types.md
Labels: 오타 / 잘못된 내용

#186 Declaration-Merging 검토
  declaration-merging.md
Labels: 오타 / 잘못된 내용

#192 Do and Don't 번역 끝
  declaration files/Do's and Don'ts.md
Labels: 번역중

#194 type checking javascript files 줄맞춤, 형식 수정.
  type-checking-javascript-files.md
Labels: 오타 / 잘못된 내용

#197 module resolution 일부 검토
  module-resolution.md
Labels: 오타 / 잘못된 내용

#190 iterators and generators 검토
  iterators-and-generators.md
Labels: 오타 / 잘못된 내용

#195 utility types 검토
  utility-types.md
Labels: 오타 / 잘못된 내용

#196 Library Structures 번역 ~ UMD (ref #144)
  declaration files/Library Structures.md
Labels: 번역중

#201 Template 일부 번역(ref #148)
  pages/declaration-files/templates/global-modifying-module.d.ts.md
  pages/declaration-files/templates/global-plugin.d.ts.md
  pages/declaration-files/templates/global.d.ts.md
Labels: 번역중

#202 Libray structrues 일부 번역 (ref #144)
  pages/declaration-files/library-structures.md
Labels: 번역중

#203 publishing 전체 번역 (ref #149)
  pages/declaration-files/publishing.md
Labels: 번역중

#211 Project Configuration 문서 추가
  README.md
  pages/compiler-options-in-msbuild.md
  pages/compiler-options.md
  pages/integrating-with-build-tools.md
  pages/nightly-builds.md
  pages/project-references.md
Labels: 계획

#209 gitbook sitemap  플러그인 추가
  book.json
  package-lock.json
  package.json
Labels: 계획

#210 Templates 번역 완료 (fix #148)
  README.md
  pages/declaration-files/templates/module-class.d.ts.md
  pages/declaration-files/templates/module-function.d.ts.md
  pages/declaration-files/templates/module-plugin.d.ts.md
  pages/declaration-files/templates/module.d.ts.md
Labels: 번역중

#221 template error 수정
  pages/declaration-files/publishing.md
  pages/type-checking-javascript-files.md
Labels: 오타 / 잘못된 내용

#214 library structures ~ 끝 (ref #144)
  pages/declaration-files/library-structures.md
Labels: 번역중

#212 consumption 전체 번역
  README.md
  pages/declaration-files/consumption.md
Labels: 번역중

#223 Tutorials/Migrating from JavaScript 번역 완료 (ref #141)
  pages/tutorials/migrating-from-javascript.md
Labels: 번역중
